import { NextFunction, Request, Response } from "express";
import { AppError } from "../middleware/errorHandler.js";

// Retired (LA-APP-COMPLETION-001 Phase H, H1). This used to call Gemini
// (study-plan/evaluate-attempt) or a provider-agnostic AI layer (explain) —
// all three had zero real frontend callers left after Phase D's rebuild
// (confirmed by grep across frontend/src before removing the implementation),
// and rule 6 of the completion directive bans AI calls anywhere in this
// build regardless. Kept as thin stubs, same convention as
// backend/src/controllers/attemptController.ts's retired submitAttempt, so
// an old client gets a clear 410 instead of a bare 404.
function retired(replacement: string) {
  return (_req: Request, _res: Response, next: NextFunction): void => {
    next(new AppError(410, "ENDPOINT_RETIRED", `This endpoint is retired — no AI calls exist in this build. ${replacement}`));
  };
}

export const generateStudyPlan = retired("Study plans are not generated by this app.");
export const evaluateAttemptAI = retired("Attempts are scored server-side arithmetically — see POST /api/assess/attempts/:attemptId/submit.");
export const explainWrongAnswer = retired("Per-question review (with the real correct answer) is available via GET /api/assess/attempts/:attemptId/review.");
