import type { CanonicalRecord } from "./types.js";

/**
 * db/scripts/dedup/survivor.ts — Section 3 of question-dedup-promptnew.md, in order:
 *
 *   1. Referenced by other tables (attempts, tests, papers).
 *   2. Valid non-null correct answer AND the full option set.
 *   3. Richest metadata (topic, difficulty, explanation, tags populated).
 *   4. Longest / most complete stem.
 *   5. Oldest created_at.
 *   6. Tiebreaker: lowest primary key.
 *
 * Each rule is a scalar score; they are compared lexicographically, highest
 * first. Every comparison is total and deterministic, so the same cluster
 * always elects the same survivor — a dry run's plan is the plan that gets
 * applied, and a re-run after a kill picks up identically.
 */

/**
 * RULE 5 HAS NO created_at TO READ, and pretending otherwise would be the
 * kind of silent no-op that makes a survivor choice arbitrary.
 *
 * content.question has 32 columns and not one of them is temporal (verified
 * against information_schema, not assumed). What DOES encode creation order
 * is question_uid: `LMN-<SUBJECT>-<NODE>-<6-digit serial>`, where the serial
 * is assigned monotonically per (subject, node) at import time
 * (schemas/question-authoring.schema.ts). Within a duplicate cluster the
 * members were generated by the same drifting pipeline into the same subject,
 * so the serial orders them the way created_at would.
 *
 * That is a substitute, not the real thing: it is only comparable WITHIN a
 * (subject, node) pair, and a cluster spanning two nodes gets an ordering
 * that means less. Which is exactly why it sits at priority 5, below three
 * content-quality rules that do not depend on it, and above only the
 * primary-key tiebreaker it would otherwise be indistinguishable from.
 *
 * Records that carry a real createdAt (file records may) use it first.
 */
function ageScore(record: CanonicalRecord): number {
  if (record.createdAt) {
    const parsed = Date.parse(record.createdAt);
    if (!Number.isNaN(parsed)) return -parsed; // older = larger score
  }
  const serial = record.questionUid?.match(/(\d{6})$/);
  if (serial) return -Number(serial[1]); // lower serial = older = larger score
  return -Number.MAX_SAFE_INTEGER;
}

/** Rule 2: a usable answer key and a complete option set. */
function answerScore(record: CanonicalRecord): number {
  const numericType = record.questionType === "integer" || record.questionType === "numeric";
  if (numericType) {
    return record.numericAnswer != null && record.numericAnswer !== "" ? 2 : 0;
  }
  const correct = record.options.filter((o) => o.isCorrect);
  const complete = record.options.length >= 2 && record.options.every((o) => o.text.trim().length > 0);
  if (correct.length >= 1 && complete) return 2;
  if (correct.length >= 1) return 1;
  return 0;
}

/** Rule 3: metadata richness — one point per populated field. */
function metadataScore(record: CanonicalRecord): number {
  let score = 0;
  if (record.nodeTagCode) score++;
  if (record.subjectCode) score++;
  if (record.difficultyBand) score++;
  if (record.explanation && record.explanation.trim().length > 0) score++;
  if (record.questionType) score++;
  return score;
}

/** Rule 1, but only counting references that are genuinely live history. */
function referenceScore(record: CanonicalRecord): number {
  return record.referenceCount ?? 0;
}

export interface SurvivorChoice {
  survivor: CanonicalRecord;
  reason: string;
}

type ScoreVector = [number, number, number, number, number, string];

function scoreOf(record: CanonicalRecord): ScoreVector {
  return [
    referenceScore(record),
    answerScore(record),
    metadataScore(record),
    record.stemText.trim().length,
    ageScore(record),
    // Rule 6 — lowest primary key wins, so it is inverted at comparison time.
    record.questionId ?? record.questionUid ?? record.stableId,
  ];
}

function compare(a: ScoreVector, b: ScoreVector): number {
  for (let i = 0; i < 5; i++) {
    const left = a[i] as number;
    const right = b[i] as number;
    if (left !== right) return right - left; // higher score first
  }
  return String(a[5]).localeCompare(String(b[5])); // lowest key first
}

export function pickSurvivor(members: CanonicalRecord[]): SurvivorChoice {
  if (members.length === 0) throw new Error("pickSurvivor called on an empty cluster");

  const ranked = members
    .map((record) => ({ record, score: scoreOf(record) }))
    .sort((x, y) => compare(x.score, y.score));

  const winner = ranked[0];
  const runnerUp = ranked[1];
  const reason = runnerUp
    ? explainRule(winner.score, runnerUp.score)
    : "only member of its cluster";

  return { survivor: winner.record, reason };
}

const RULE_NAMES = [
  "referenced by live history",
  "has a valid answer and a complete option set",
  "richest metadata",
  "longest stem",
  "oldest (question_uid serial)",
];

function explainRule(winner: ScoreVector, runnerUp: ScoreVector): string {
  for (let i = 0; i < 5; i++) {
    if (winner[i] !== runnerUp[i]) {
      return "rule " + (i + 1) + ": " + RULE_NAMES[i] + " (" + winner[i] + " vs " + runnerUp[i] + ")";
    }
  }
  return "rule 6: lowest primary key";
}

/**
 * Section 3: "Merge non-conflicting metadata upward into the survivor (e.g.
 * survivor missing `explanation`, loser has one -> copy it)."
 *
 * NON-CONFLICTING is load-bearing: a field is only merged when the survivor's
 * copy is absent. A populated survivor field is never overwritten by a
 * loser's, because the survivor won on rules that already weighed content
 * quality and the loser is a drift artefact.
 */
export interface MetadataMerge {
  difficultyBand?: string;
  explanation?: string;
  nodeTagCode?: string;
  subjectCode?: string;
  questionType?: string;
}

export function computeMetadataMerge(
  survivor: CanonicalRecord,
  losers: CanonicalRecord[]
): MetadataMerge {
  const merge: MetadataMerge = {};
  const take = (
    key: keyof MetadataMerge,
    read: (record: CanonicalRecord) => string | null | undefined
  ) => {
    if (read(survivor)) return;
    for (const loser of losers) {
      const value = read(loser);
      if (value && value.trim().length > 0) {
        merge[key] = value;
        return;
      }
    }
  };

  take("difficultyBand", (r) => r.difficultyBand);
  take("explanation", (r) => r.explanation);
  take("nodeTagCode", (r) => r.nodeTagCode);
  take("subjectCode", (r) => r.subjectCode);
  take("questionType", (r) => r.questionType);
  return merge;
}
