import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ta';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<Language, string>> = {
  "AI-Powered 720 Score Master Plan": { en: "AI-Powered 720 Score Master Plan", ta: "AI-ஆதரவு 720 மதிப்பெண் முதன்மை திட்டம்" },
  "Welcome, ": { en: "Welcome, ", ta: "வரவேற்கிறோம், " },
  "! Our AI model calculates your ideal study cadence, chapter sequence, and daily routine to maximize your All-India Rank (AIR).": { en: "! Our AI model calculates your ideal study cadence, chapter sequence, and daily routine to maximize your All-India Rank (AIR).", ta: "! உங்கள் அகில இந்திய தரவரிசையை (AIR) அதிகரிக்க உங்கள் சிறந்த படிப்பு வேகம், அத்தியாய வரிசை மற்றும் தினசரி வழக்கத்தை எங்கள் AI மாதிரி கணக்கிடுகிறது." },
  "Target Score: 720 / 720": { en: "Target Score: 720 / 720", ta: "இலக்கு மதிப்பெண்: 720 / 720" },
  "Optimized Time-Blocking": { en: "Optimized Time-Blocking", ta: "உகந்த நேர ஒதுக்கீடு" },
  "AI Weakness Remediation": { en: "AI Weakness Remediation", ta: "AI பலவீன தீர்வு" },
  "Neet Syllabus": { en: "Neet Syllabus", ta: "NEET பாடத்திட்டம்" },
  "Build Study Plan": { en: "Build Study Plan", ta: "படிப்பு திட்டத்தை உருவாக்கு" },
  "Course Overview": { en: "Course Overview", ta: "பாடத்தின் கண்ணோட்டம்" },
  "Welcome to the Lumen Academy Course portal. Here you can explore the complete NEET syllabus,              access comprehensive study materials, and build a personalized study plan to track your progress and achieve your goals.": { en: "Welcome to the Lumen Academy Course portal. Here you can explore the complete NEET syllabus,              access comprehensive study materials, and build a personalized study plan to track your progress and achieve your goals.", ta: "லூமன் அகாடமி பாடத்திட்ட போர்ட்டலுக்கு வருக. இங்கே நீங்கள் முழுமையான NEET பாடத்திட்டத்தை ஆராயலாம், விரிவான ஆய்வுப் பொருட்களை அணுகலாம் மற்றும் உங்கள் முன்னேற்றத்தைக் கண்காணிக்கவும் உங்கள் இலக்குகளை அடையவும் தனிப்பயனாக்கப்பட்ட படிப்புத் திட்டத்தை உருவாக்கலாம்." },

  "10 Qs": { en: "10 Qs", ta: "10 கேள்விகள்" },
  "20 Qs": { en: "20 Qs", ta: "20 கேள்விகள்" },
  "30 Qs": { en: "30 Qs", ta: "30 கேள்விகள்" },
  "40 Qs": { en: "40 Qs", ta: "40 கேள்விகள்" },
  "50 Qs": { en: "50 Qs", ta: "50 கேள்விகள்" },
  "60 Qs": { en: "60 Qs", ta: "60 கேள்விகள்" },
  "70 Qs": { en: "70 Qs", ta: "70 கேள்விகள்" },
  "80 Qs": { en: "80 Qs", ta: "80 கேள்விகள்" },
  "90 Qs": { en: "90 Qs", ta: "90 கேள்விகள்" },
  "100 Qs": { en: "100 Qs", ta: "100 கேள்விகள்" },

  "View Scorecard": { en: "View Scorecard", ta: "மதிப்பெண் அட்டையைக் காண்" },
  "Start Mock Test": { en: "Start Mock Test", ta: "மாதிரி தேர்வைத் தொடங்கு" },
  "Locked (Complete Syllabus Tracker)": { en: "Locked (Complete Syllabus Tracker)", ta: "பூட்டப்பட்டுள்ளது (முழு பாடத்திட்ட கண்காணிப்பு)" },
  "Custom Calibration": { en: "Custom Calibration", ta: "தனிப்பயன் அளவுத்திருத்தம்" },

  "Biology Focus": { en: "Biology Focus", ta: "உயிரியல் கவனம்" },
  "Chemistry Focus": { en: "Chemistry Focus", ta: "வேதியியல் கவனம்" },
  "Physics, Chemistry, Biology Complete Syllabus": { en: "Physics, Chemistry, Biology Complete Syllabus", ta: "இயற்பியல், வேதியியல், உயிரியல் முழு பாடத்திட்டம்" },
  "Genetics, Evolution, Ecology": { en: "Genetics, Evolution, Ecology", ta: "மரபியல், பரிணாமம், சூழலியல்" },
  "p-Block Elements, Periodic Trends": { en: "p-Block Elements, Periodic Trends", ta: "p-பிளாக் தனிமங்கள், காலமுறை போக்குகள்" },
  "NEET Full Syllabus Mock 04": { en: "NEET Full Syllabus Mock 04", ta: "NEET முழு பாடத்திட்ட மாதிரி தேர்வு 04" },
  "NEET Full Syllabus Mock 05 (720 Marks)": { en: "NEET Full Syllabus Mock 05 (720 Marks)", ta: "NEET முழு பாடத்திட்ட மாதிரி தேர்வு 05 (720 மதிப்பெண்கள்)" },
  "NEET Biology Mini-Mock #12": { en: "NEET Biology Mini-Mock #12", ta: "NEET உயிரியல் மினி-மாதிரி தேர்வு #12" },
  "NEET Chemistry Mini-Mock #08": { en: "NEET Chemistry Mini-Mock #08", ta: "NEET வேதியியல் மினி-மாதிரி தேர்வு #08" },

  "mins": { en: "mins", ta: "நிமிடங்கள்" },
  "Mins (Strict)": { en: "Mins (Strict)", ta: "நிமிடங்கள் (கண்டிப்பானது)" },

  "Dashboard": { en: "Dashboard", ta: "டாஷ்போர்டு" },
  "Course": { en: "Course", ta: "படிப்புகள்" },
  "Tests": { en: "Tests", ta: "தேர்வுகள்" },
  "Analytics": { en: "Analytics", ta: "பகுப்பாய்வு" },
  "Great work, princeprince45613!": { en: "Great work, princeprince45613!", ta: "சிறப்பான செயல்பாடு, princeprince45613!" },
  "% of participants": { en: "% of participants", ta: "% பங்கேற்பாளர்களை விட" },
  ". Your consistency in Physics is showing significant growth.": { en: ". Your consistency in Physics is showing significant growth.", ta: " சிறப்பாக செயல்பட்டுள்ளீர்கள். இயற்பியலில் உங்கள் நிலைத்தன்மை கணிசமான வளர்ச்சியைக் காட்டுகிறது." },
  "Deep Diagnostics & Analytics": { en: "Deep Diagnostics & Analytics", ta: "ஆழமான கண்டறிதல் & பகுப்பாய்வு" },
  "Granular performance tracking and trends over your last completed mock sessions.": { en: "Granular performance tracking and trends over your last completed mock sessions.", ta: "உங்கள் கடைசியாக முடிக்கப்பட்ட மாதிரி தேர்வுகளில் துல்லியமான செயல்திறன் கண்காணிப்பு மற்றும் போக்குகள்." },
  "Trend Evaluation Overview": { en: "Trend Evaluation Overview", ta: "போக்கு மதிப்பீட்டு கண்ணோட்டம்" },
  "Overall percentile and total correct score distribution": { en: "Overall percentile and total correct score distribution", ta: "ஒட்டுமொத்த சதவீதம் மற்றும் மொத்த சரியான மதிப்பெண் விநியோகம்" },
  "Available": { en: "Available", ta: "கிடைக்கிறது" },
  "* Trend reflects performance over the last completed sessions": { en: "* Trend reflects performance over the last completed sessions", ta: "* போக்கு கடைசியாக முடிக்கப்பட்ட தேர்வுகளில் செயல்திறனைக் காட்டுகிறது" },
  "Trend: ": { en: "Trend: ", ta: "போக்கு: " },
  "% Improvement": { en: "% Improvement", ta: "% மேம்பாடு" },
  "Weakness Analysis": { en: "Weakness Analysis", ta: "பலவீனப் பகுப்பாய்வு" },
  "Subject categories with high error densities": { en: "Subject categories with high error densities", ta: "அதிக பிழை உள்ள பாடப் பிரிவுகள்" },
  "Review": { en: "Review", ta: "மதிப்பாய்வு" },
  "Generate AI Revision Sheets": { en: "Generate AI Revision Sheets", ta: "AI திருப்புதல் தாள்களை உருவாக்கு" },
  "Complete NEET Syllabus & Unit Mock Tests": { en: "Complete NEET Syllabus & Unit Mock Tests", ta: "முழுமையான NEET பாடத்திட்டம் & அலகு மாதிரி தேர்வுகள்" },
  "Explore all 24 NTA-aligned units across Physics, Chemistry, Botany, and Zoology. Study high-yield NCERT notes, access formula cheatsheets, and take targeted unit mock tests.": { en: "Explore all 24 NTA-aligned units across Physics, Chemistry, Botany, and Zoology. Study high-yield NCERT notes, access formula cheatsheets, and take targeted unit mock tests.", ta: "இயற்பியல், வேதியியல், தாவரவியல் மற்றும் விலங்கியல் ஆகியவற்றில் உள்ள அனைத்து 24 NTA-அடிப்படையிலான அலகுகளையும் ஆராயுங்கள். NCERT குறிப்புகளைப் படியுங்கள் மற்றும் இலக்கு மாதிரி தேர்வுகளை எழுதுங்கள்." },
  "24 High-Yield Units": { en: "24 High-Yield Units", ta: "24 முக்கிய அலகுகள்" },
  "24 Dedicated Unit Mocks": { en: "24 Dedicated Unit Mocks", ta: "24 சிறப்பு அலகு தேர்வுகள்" },
  "96+ NCERT Study PDF Materials": { en: "96+ NCERT Study PDF Materials", ta: "96+ NCERT படிப்பு PDF பொருட்கள்" },
  "NEET Course Units & Modules": { en: "NEET Course Units & Modules", ta: "NEET பாட அலகுகள் & தொகுதிகள்" },
  "Select a subject or unit to view its complete syllabus, materials, and launch a mock test.": { en: "Select a subject or unit to view its complete syllabus, materials, and launch a mock test.", ta: "முழுமையான பாடத்திட்டம், பொருட்கள் மற்றும் மாதிரி தேர்வைக் காண ஒரு பாடம் அல்லது அலகைத் தேர்ந்தெடுக்கவும்." },
  "Search units, topics, chapters...": { en: "Search units, topics, chapters...", ta: "அலகுகள், தலைப்புகள், அத்தியாயங்களைத் தேடுங்கள்..." },
  "All Subjects": { en: "All Subjects", ta: "அனைத்து பாடங்களும்" },
  "All Classes": { en: "All Classes", ta: "அனைத்து வகுப்புகளும்" },
  "Class 11": { en: "Class 11", ta: "வகுப்பு 11" },
  "Class 12": { en: "Class 12", ta: "வகுப்பு 12" },
  "NEET Mock Test Series": { en: "NEET Mock Test Series", ta: "NEET மாதிரி தேர்வுத் தொடர்" },
  "Challenge yourself with high-fidelity examination environments and get instant, smart AI strategies.": { en: "Challenge yourself with high-fidelity examination environments and get instant, smart AI strategies.", ta: "உயர்-துல்லிய தேர்வு சூழல்களுடன் உங்களை சோதித்து, உடனடி AI உத்திகளைப் பெறுங்கள்." },
  "ALL SUBJECTS": { en: "ALL SUBJECTS", ta: "அனைத்து பாடங்களும்" },
  "AVAILABLE": { en: "AVAILABLE", ta: "கிடைக்கிறது" },
  "Complete Syllabus": { en: "Complete Syllabus", ta: "முழு பாடத்திட்டம்" },
  "180 Questions": { en: "180 Questions", ta: "180 கேள்விகள்" },
  "180 mins": { en: "180 mins", ta: "180 நிமிடங்கள்" },
  "VIEW SCORECARD": { en: "VIEW SCORECARD", ta: "மதிப்பெண் அட்டையைக் காண்" },
  "LOCKED (COMPLETE SYLLABUS TRACKER)": { en: "LOCKED (COMPLETE SYLLABUS TRACKER)", ta: "பூட்டப்பட்டுள்ளது (முழு பாடத்திட்ட கண்காணிப்பு)" },
  "BIOLOGY FOCUS": { en: "BIOLOGY FOCUS", ta: "உயிரியல் கவனம்" },
  "10 Questions": { en: "10 Questions", ta: "10 கேள்விகள்" },
  "10 mins": { en: "10 mins", ta: "10 நிமிடங்கள்" },
  "START MOCK TEST": { en: "START MOCK TEST", ta: "மாதிரி தேர்வைத் தொடங்கு" },
  "CHEMISTRY FOCUS": { en: "CHEMISTRY FOCUS", ta: "வேதியியல் கவனம்" },
  "CUSTOM CALIBRATION": { en: "CUSTOM CALIBRATION", ta: "தனிப்பயன் அளவுத்திருத்தம்" },
  "Custom Mock Builder": { en: "Custom Mock Builder", ta: "தனிப்பயன் மாதிரி தேர்வு உருவாக்கி" },
  "No mock tests completed yet.": { en: "No mock tests completed yet.", ta: "இதுவரை எந்த மாதிரி தேர்வுகளும் முடிக்கப்படவில்லை." },
  "Take a mock test to see your weakness analysis.": { en: "Take a mock test to see your weakness analysis.", ta: "உங்கள் பலவீன பகுப்பாய்வைக் காண ஒரு மாதிரி தேர்வை எழுதவும்." },

  " among candidates. The steep slope of your Item Characteristic Curve (Discrimination ": { en: " among candidates. The steep slope of your Item Characteristic Curve (Discrimination ", ta: " பங்கேற்பாளர்கள் இடையே. உங்கள் கேள்வி பண்பு வளைவின் செங்குத்தான சாய்வு (வேறுபாடு " },
  ") indicates high reliability.": { en: ") indicates high reliability.", ta: ") அதிக நம்பகத்தன்மையைக் குறிக்கிறது." },
  "a = 0.92": { en: "a = 0.92", ta: "a = 0.92" },

  "Highest Velocity": { en: "Highest Velocity", ta: "அதிக வேகம்" },
  "Chronometric Friction": { en: "Chronometric Friction", ta: "குரோனோமெட்ரிக் உராய்வு" },
  "Discrimination (a)": { en: "Discrimination (a)", ta: "வேறுபாடு (a)" },
  "Difficulty Threshold": { en: "Difficulty Threshold", ta: "கடினத்தன்மை வரம்பு" },
  " Focus exclusively on high-complexity threshold questions. Your growth margin is entirely in the uppermost difficulty tier.": { en: " Focus exclusively on high-complexity threshold questions. Your growth margin is entirely in the uppermost difficulty tier.", ta: " அதிக கடினத்தன்மை கொண்ட கேள்விகளில் மட்டும் கவனம் செலுத்துங்கள். உங்கள் வளர்ச்சி முற்றிலும் உயர் கடினத்தன்மை அடுக்கில் உள்ளது." },

  " You have a 99% probability of answering items with difficulty (b) < 0.5 correctly.": { en: " You have a 99% probability of answering items with difficulty (b) < 0.5 correctly.", ta: " கடினத்தன்மை (b) < 0.5 உள்ள கேள்விகளுக்கு நீங்கள் சரியாக பதிலளிக்க 99% வாய்ப்பு உள்ளது." },
  "Item Characteristic Curve & Psychometric Analysis": { en: "Item Characteristic Curve & Psychometric Analysis", ta: "கேள்வி பண்பு வளைவு & உளவியல் பகுப்பாய்வு" },
  "Item Characteristic Curve (ICC)": { en: "Item Characteristic Curve (ICC)", ta: "கேள்வி பண்பு வளைவு (ICC)" },
  "IRT Diagnostic Report": { en: "IRT Diagnostic Report", ta: "IRT கண்டறிதல் அறிக்கை" },
  " in the ": { en: " in the ", ta: " இதில் " },
  "How To Improve:": { en: "How To Improve:", ta: "எப்படி மேம்படுத்துவது:" },
  "Average Time / Question": { en: "Average Time / Question", ta: "சராசரி நேரம் / கேள்வி" },
  "High Growth Potential": { en: "High Growth Potential", ta: "அதிக வளர்ச்சி திறன்" },
  "Needs Immediate Attention": { en: "Needs Immediate Attention", ta: "உடனடி கவனம் தேவை" },
  "Consolidated Rank Insight": { en: "Consolidated Rank Insight", ta: "ஒருங்கிணைந்த தரவரிசை தகவல்" },
  "Projected Exam Readiness based on psychometric trait convergence": { en: "Projected Exam Readiness based on psychometric trait convergence", ta: "உளவியல் பண்புகளின் அடிப்படையில் கணிக்கப்பட்ட தேர்வு தயார்நிலை" },
  "Based on global cognitive trait distribution": { en: "Based on global cognitive trait distribution", ta: "உலகளாவிய அறிவாற்றல் திறன் விநியோகத்தின் அடிப்படையில்" },
  "Your Cognitive Trait": { en: "Your Cognitive Trait", ta: "உங்கள் அறிவாற்றல் திறன்" },
  "Subject Performance Diagnostics": { en: "Subject Performance Diagnostics", ta: "பாட செயல்திறன் கண்டறிதல்" },
  "Time velocity tracking...": { en: "Time velocity tracking...", ta: "நேர வேகம் கண்காணிக்கப்படுகிறது..." },

  "Security & Login": { en: "Security & Login", ta: "பாதுகாப்பு & உள்நுழைவு" },
  "Display & Theme": { en: "Display & Theme", ta: "காட்சி & தோற்றம்" },

  "Item Response Theory (IRT) Profiling": { en: "Item Response Theory (IRT) Profiling", ta: "கேள்வி பதில் கோட்பாடு (IRT) விவரக்குறிப்பு" },
  "Advanced psychometric analysis based on your response patterns, mapping your cognitive ability against item difficulty and identifying potential lucky guesses versus true conceptual mastery.": { en: "Advanced psychometric analysis based on your response patterns, mapping your cognitive ability against item difficulty and identifying potential lucky guesses versus true conceptual mastery.", ta: "உங்கள் பதில் முறைகளின் அடிப்படையில் மேம்பட்ட உளவியல் பகுப்பாய்வு, கேள்வி கடினத்தன்மைக்கு எதிராக உங்கள் அறிவாற்றல் திறனை வரைபடமாக்குதல் மற்றும் உண்மையான கருத்தியல் தேர்ச்சிக்கு எதிராக சாத்தியமான அதிர்ஷ்டமான யூகங்களை அடையாளம் காணுதல்." },
  "DIFFICULTY THRESHOLD": { en: "DIFFICULTY THRESHOLD", ta: "கடினத்தன்மை வரம்பு" },
  "High": { en: "High", ta: "அதிகம்" },
  "DISCRIMINATION (A)": { en: "DISCRIMINATION (A)", ta: "வேறுபாடு (A)" },
  "High correlation between your overall ability and performance on complex items.": { en: "High correlation between your overall ability and performance on complex items.", ta: "உங்கள் ஒட்டுமொத்த திறனுக்கும் சிக்கலான கேள்விகளில் உங்கள் செயல்திறனுக்கும் இடையே அதிக தொடர்பு." },
  "AI Diagnostic & Strategy Report": { en: "AI Diagnostic & Strategy Report", ta: "AI கண்டறிதல் மற்றும் உத்தி அறிக்கை" },
  "Deep concept gap analysis with exact NCERT textbook references": { en: "Deep concept gap analysis with exact NCERT textbook references", ta: "சரியான NCERT பாடநூல் குறிப்புகளுடன் ஆழமான கருத்தியல் இடைவெளி பகுப்பாய்வு" },
  "we recommend prioritising": { en: "we recommend prioritising", ta: "இதற்கு முன்னுரிமை அளிக்க பரிந்துரைக்கிறோம்:" },
  "and": { en: "and", ta: "மற்றும்" },
  "Addressing these specific gaps can yield an immediate gain of": { en: "Addressing these specific gaps can yield an immediate gain of", ta: "இந்தக் குறிப்பிட்ட இடைவெளிகளை நிவர்த்தி செய்வதன் மூலம் உங்கள் அடுத்த மாதிரி தேர்வில்" },
  "in your next mock.": { en: "in your next mock.", ta: "உடனடி லாபத்தைப் பெறலாம்." },
  "START TARGETED DRILLS": { en: "START TARGETED DRILLS", ta: "இலக்கு பயிற்சிகளைத் தொடங்கு" },
  "OPEN FULL NCERT LAGGING REPORT": { en: "OPEN FULL NCERT LAGGING REPORT", ta: "முழு NCERT பின்னடைவு அறிக்கையைத் திற" },
  "CORE FOCUS TOPICS": { en: "CORE FOCUS TOPICS", ta: "முக்கிய கவனம் செலுத்தும் தலைப்புகள்" },
  "CRITICAL": { en: "CRITICAL", ta: "சிக்கலானது" },
  "IMPROVEMENT": { en: "IMPROVEMENT", ta: "மேம்பாடு" },
  "DONE": { en: "DONE", ta: "முடிந்தது" },
  "Individual accuracy and growth breakdown across core NEET syllabus": { en: "Individual accuracy and growth breakdown across core NEET syllabus", ta: "முக்கிய NEET பாடத்திட்டம் முழுவதும் தனிப்பட்ட துல்லியம் மற்றும் வளர்ச்சி முறிவு" },
  "Compare with Previous": { en: "Compare with Previous", ta: "முந்தையதுடன் ஒப்பிடுக" },
  "STRONG": { en: "STRONG", ta: "வலுவானது" },
  "AVERAGE": { en: "AVERAGE", ta: "சராசரி" },
  "EXPERT": { en: "EXPERT", ta: "வல்லுநர்" },
  "Real-time chronometrics mapping your cognitive velocity across different subjects and difficulty tiers.": { en: "Real-time chronometrics mapping your cognitive velocity across different subjects and difficulty tiers.", ta: "வெவ்வேறு பாடங்கள் மற்றும் கடினத்தன்மை அடுக்குகளில் உங்கள் அறிவாற்றல் வேகத்தை வரைபடமாக்கும் நிகழ்நேர குரோனோமெட்ரிக்ஸ்." },
  "AVERAGE TIME / QUESTION": { en: "AVERAGE TIME / QUESTION", ta: "சராசரி நேரம் / கேள்வி" },
  "seconds": { en: "seconds", ta: "வினாடிகள்" },
  "HIGHEST VELOCITY": { en: "HIGHEST VELOCITY", ta: "அதிக வேகம்" },
  "s / question": { en: "s / question", ta: "வி / கேள்வி" },
  "CHRONOMETRIC FRICTION": { en: "CHRONOMETRIC FRICTION", ta: "குரோனோமெட்ரிக் உராய்வு" },
  "Based on your results in": { en: "Based on your results in", ta: "இதன் முடிவுகளின் அடிப்படையில்" },

  "Evaluating your test...": { en: "Evaluating your test...", ta: "உங்கள் தேர்வு மதிப்பிடப்படுகிறது..." },
  "Analyzing accuracy metrics": { en: "Analyzing accuracy metrics", ta: "துல்லியத்தை ஆராய்கிறது" },
  "Generating deep insights...": { en: "Generating deep insights...", ta: "ஆழ்ந்த நுண்ணறிவுகளை உருவாக்குகிறது..." },
  "Preparing report for NEET Biology Mini-Mock #12": { en: "Preparing report for NEET Biology Mini-Mock #12", ta: "அறிக்கை தயாராகிறது..." },
  "Almost there...": { en: "Almost there...", ta: "கிட்டத்தட்ட முடிந்துவிட்டது..." },
  "Mapping progress to Biology, Chemistry & Physics": { en: "Mapping progress to Biology, Chemistry & Physics", ta: "செயல்திறன் மதிப்பிடப்படுகிறது..." },
  "Analysis Complete!": { en: "Analysis Complete!", ta: "பகுப்பாய்வு முடிந்தது!" },
  "Redirecting to your scorecard": { en: "Redirecting to your scorecard", ta: "உங்கள் மதிப்பெண் அட்டைக்கு செல்கிறது" },
  "Test Rules": { en: "Test Rules", ta: "தேர்வு விதிகள்" },
  "Standard Examination Session": { en: "Standard Examination Session", ta: "நிலையான தேர்வு அமர்வு" },
  "Scoring Matrix": { en: "Scoring Matrix", ta: "மதிப்பெண் முறை" },
  "Correct Response": { en: "Correct Response", ta: "சரியான பதில்" },
  "Incorrect Response": { en: "Incorrect Response", ta: "தவறான பதில்" },
  "Unattempted": { en: "Unattempted", ta: "முயற்சிக்காதவை" },
  "Auto-Submission": { en: "Auto-Submission", ta: "தானியங்கி சமர்ப்பிப்பு" },
  "No tab switching": { en: "No tab switching", ta: "தாவல்களை (tab) மாற்றக் கூடாது" },
  "Pending": { en: "Pending", ta: "நிலுவையில் உள்ளது" },
  "Web Browser Compatibility": { en: "Web Browser Compatibility", ta: "உலாவி பொருத்தம்" },
  "Test Type": { en: "Test Type", ta: "தேர்வு வகை" },
  "Target Exam": { en: "Target Exam", ta: "இலக்கு தேர்வு" },
  "System Memory & Execution Readiness": { en: "System Memory & Execution Readiness", ta: "கணினி நினைவகம் மற்றும் தயார்நிலை" },
  "Prince A": { en: "Prince A", ta: "பிரிட்ஸ் ஏ" },
  "NEET UG 2026": { en: "NEET UG 2026", ta: "NEET UG 2026" },
  "Full-Syllabus Mock Exam": { en: "Full-Syllabus Mock Exam", ta: "முழு-பாடத்திட்ட மாதிரி தேர்வு" },
  "Display & Resolution Scaling": { en: "Display & Resolution Scaling", ta: "காட்சி மற்றும் தெளிவுத்திறன்" },
  "Diagnostics Status": { en: "Diagnostics Status", ta: "பகுப்பாய்வு நிலை" },
  "Connection Latency & Bandwidth": { en: "Connection Latency & Bandwidth", ta: "இணைப்பு தாமதம் மற்றும் அலைவரிசை" },
  "App No: N-2026-894723": { en: "App No: N-2026-894723", ta: "விண்ணப்ப எண்: N-2026-894723" },
  "Start Exam System Check": { en: "Start Exam System Check", ta: "தேர்வு அமைப்பு சரிபார்ப்பைத் தொடங்குக" },
  "Continue to Lobby": { en: "Continue to Lobby", ta: "லாபிக்கு தொடரவும்" },
  "Begin Diagnostics": { en: "Begin Diagnostics", ta: "பகுப்பாய்வை தொடங்குக" },
  "Begin": { en: "Begin", ta: "தொடங்கவும்" },
  "System Checks Passed": { en: "System Checks Passed", ta: "அமைப்பு சோதனைகள் வெற்றி" },
  "I am ready to begin": { en: "I am ready to begin", ta: "நான் தொடங்க தயாராக உள்ளேன்" },
  "Read rules and check settings carefully before starting.": { en: "Read rules and check settings carefully before starting.", ta: "தொடங்குவதற்கு முன் விதிகள் மற்றும் அமைப்புகளை கவனமாகப் படிக்கவும்." },

  "Your Inorganic Chemistry accuracy was 76% in Mock 04.": { en: "Your Inorganic Chemistry accuracy was 76% in Mock 04.", ta: "Mock 04 இல் உங்கள் கனிம வேதியியல் துல்லியம் 76% ஆக இருந்தது." },

  "View Results": { en: "View Results", ta: "முடிவுகளைக் காண்" },
  "WhatsApp Result Alerts": { en: "WhatsApp Result Alerts", ta: "WhatsApp முடிவு எச்சரிக்கைகள்" },
  "Verify OTP on new browser logins": { en: "Verify OTP on new browser logins", ta: "புதிய உலாவி உள்நுழைவுகளில் OTP-ஐ சரிபார்க்கவும்" },
  "Verified Student": { en: "Verified Student", ta: "சரிபார்க்கப்பட்ட மாணவர்" },
  "Valid till May 2026 • Full Test Series": { en: "Valid till May 2026 • Full Test Series", ta: "மே 2026 வரை செல்லுபடியாகும் • முழு தேர்வுத் தொடர்" },
  "Valid till May 2026": { en: "Valid till May 2026", ta: "மே 2026 வரை செல்லுபடியாகும்" },
  "Urgent Focus Required": { en: "Urgent Focus Required", ta: "அவசர கவனம் தேவை" },
  "Two-Factor Authentication (2FA)": { en: "Two-Factor Authentication (2FA)", ta: "இரண்டு காரணி அங்கீகாரம் (2FA)" },
  "Test your concepts on Genetics and Evolution.": { en: "Test your concepts on Genetics and Evolution.", ta: "மரபியல் மற்றும் பரிணாம வளர்ச்சியில் உங்கள் கருத்துக்களை சோதிக்கவும்." },
  "Tests Attempted": { en: "Tests Attempted", ta: "முயற்சிக்கப்பட்ட தேர்வுகள்" },
  "Security & Credentials": { en: "Security & Credentials", ta: "பாதுகாப்பு மற்றும் நற்சான்றிதழ்கள்" },
  "Pro": { en: "Pro", ta: "ப்ரோ" },
  "Predicted AIR": { en: "Predicted AIR", ta: "கணிக்கப்பட்ட AIR" },
  "Package Details": { en: "Package Details", ta: "தொகுப்பு விவரங்கள்" },
  "NTA Exam Palette Mode": { en: "NTA Exam Palette Mode", ta: "NTA தேர்வு தட்டு முறை" },
  "Notifications": { en: "Notifications", ta: "அறிவிப்புகள்" },
  "Notifications (2)": { en: "Notifications (2)", ta: "அறிவிப்புகள் (2)" },
  "Notification Preferences": { en: "Notification Preferences", ta: "அறிவிப்பு விருப்பங்கள்" },
  "NEET Aspirant": { en: "NEET Aspirant", ta: "NEET மாணவர்" },
  "Mock Test 04 Evaluated": { en: "Mock Test 04 Evaluated", ta: "மாதிரி தேர்வு 04 மதிப்பீடு செய்யப்பட்டது" },
  "Micro-Mock Available": { en: "Micro-Mock Available", ta: "Micro-Mock கிடைக்கிறது" },
  "Log Out": { en: "Log Out", ta: "வெளியேறு" },
  "Light & Dark theme optimized for 3-hour exam sessions to minimize eye strain.": { en: "Light & Dark theme optimized for 3-hour exam sessions to minimize eye strain.", ta: "கண் சோர்வைக் குறைக்க 3 மணி நேர தேர்வு அமர்வுகளுக்காக வடிவமைக்கப்பட்ட லைட் & டார்க் தீம்." },
  "Email AIR Diagnostic Cards": { en: "Email AIR Diagnostic Cards", ta: "மின்னஞ்சல் மூலம் AIR கண்டறியும் அட்டைகள்" },
  "Display & Appearance": { en: "Display & Appearance", ta: "காட்சி மற்றும் தோற்றம்" },
  "Daily push notifications for weak NCERT topics": { en: "Daily push notifications for weak NCERT topics", ta: "பலவீனமான NCERT தலைப்புகளுக்கான தினசரி அறிவிப்புகள்" },
  "Daily Revision Reminders": { en: "Daily Revision Reminders", ta: "தினசரி திருப்புதல் நினைவூட்டல்கள்" },
  "Choose how and when to receive performance updates": { en: "Choose how and when to receive performance updates", ta: "செயல்திறன் புதுப்பிப்புகளை எப்போது, எப்படிப் பெறுவது என்பதைத் தேர்வுசெய்யவும்" },
  "Active: High-Contrast Exam Mode": { en: "Active: High-Contrast Exam Mode", ta: "செயலில் உள்ளது: உயர்-மாறுபட்ட தேர்வு முறை" },
  "Active": { en: "Active", ta: "செயலில் உள்ளது" },
  "Manage your account security and authentication methods.": { en: "Manage your account security and authentication methods.", ta: "உங்கள் கணக்கு பாதுகாப்பு மற்றும் அங்கீகார முறைகளை நிர்வகிக்கவும்." },
  "Instant WhatsApp summary after test completion": { en: "Instant WhatsApp summary after test completion", ta: "தேர்வு முடிந்ததும் உடனடி WhatsApp சுருக்கம்" },
  "Send detailed score reports to parent/student email": { en: "Send detailed score reports to parent/student email", ta: "பெற்றோர்/மாணவர் மின்னஞ்சலுக்கு விரிவான மதிப்பெண் அறிக்கைகளை அனுப்பவும்" },

  "LATENT ABILITY (θ)": { en: "LATENT ABILITY (θ)", ta: "மறைந்திருக்கும் திறன் (θ)" },
  "Latent Ability (θ)": { en: "Latent Ability (θ)", ta: "மறைந்திருக்கும் திறன் (θ)" },
  "No Major Concept Lags Detected!": { en: "No Major Concept Lags Detected!", ta: "பெரிய கருத்துப் பிழைகள் எதுவும் கண்டறியப்படவில்லை!" },
  "Probability of answering correctly by guessing on unknown items is low.": { en: "Probability of answering correctly by guessing on unknown items is low.", ta: "தெரியாத கேள்விகளில் ஊகிப்பதன் மூலம் சரியாக பதிலளிப்பதற்கான வாய்ப்பு குறைவு." },
  "Low Guessing Dependency:": { en: "Low Guessing Dependency:", ta: "குறைந்த ஊகிக்கும் சார்பு:" },
  " places you in the ": { en: " places you in the ", ta: " உங்களை வைக்கிறது " },
  "Review answered, flagged, and skipped questions": { en: "Review answered, flagged, and skipped questions", ta: "பதிலளிக்கப்பட்ட, குறிக்கப்பட்ட மற்றும் தவிர்க்கப்பட்ட கேள்விகளை மதிப்பாய்வு செய்யவும்" },
  "Question Palette": { en: "Question Palette", ta: "கேள்வி பலகை" },
  "Practice Mode Assistance": { en: "Practice Mode Assistance", ta: "பயிற்சி முறை உதவி" },
  "Flag for review and answered": { en: "Flag for review and answered", ta: "மதிப்பாய்வுக்காக குறிக்கப்பட்டு பதிலளிக்கப்பட்டது" },
  "Flag for review": { en: "Flag for review", ta: "மதிப்பாய்வுக்கு குறிக்கவும்" },
  "Correct Option:": { en: "Correct Option:", ta: "சரியான விருப்பம்:" },
  "180 Qs (Full)": { en: "180 Qs (Full)", ta: "180 கேள்விகள் (முழு)" },
  "Full": { en: "Full", ta: "முழு" },

  "Temporal Analytics": { en: "Temporal Analytics", ta: "நேரஞ்சார்ந்த பகுப்பாய்வு" },
  "Target Percentile": { en: "Target Percentile", ta: "இலக்கு சதவீதம்" },
  "Subject Performance": { en: "Subject Performance", ta: "பாட செயல்திறன்" },
  "Skipped Questions": { en: "Skipped Questions", ta: "தவிர்க்கப்பட்ட கேள்விகள்" },
  "Score": { en: "Score", ta: "மதிப்பெண்" },
  "Return to Dashboard": { en: "Return to Dashboard", ta: "டாஷ்போர்டுக்கு திரும்பு" },
  "Question Responses Distribution": { en: "Question Responses Distribution", ta: "கேள்வி பதில்களின் விநியோகம்" },
  "Performance Diagnostics": { en: "Performance Diagnostics", ta: "செயல்திறன் கண்டறிதல்" },
  "Overview": { en: "Overview", ta: "கண்ணோட்டம்" },
  "Needs Work": { en: "Needs Work", ta: "கவனம் தேவை" },
  "Model Fit": { en: "Model Fit", ta: "மாதிரி பொருத்தம்" },
  "Missing / Skipped": { en: "Missing / Skipped", ta: "விடுபட்டவை / தவிர்க்கப்பட்டவை" },
  "Minutes": { en: "Minutes", ta: "நிமிடங்கள்" },
  "Minute": { en: "Minute", ta: "நிமிடம்" },
  "Key Insights": { en: "Key Insights", ta: "முக்கிய தகவல்கள்" },
  "Item Response Curve": { en: "Item Response Curve", ta: "கேள்வி பதில் வளைவு" },
  "Incorrect Answers": { en: "Incorrect Answers", ta: "தவறான பதில்கள்" },
  "Immediate Actions:": { en: "Immediate Actions:", ta: "உடனடி செயல்கள்:" },
  "Focus Area": { en: "Focus Area", ta: "கவனம் செலுத்த வேண்டிய பகுதி" },
  "Excellent": { en: "Excellent", ta: "மிக நன்று" },
  "Detailed Analysis": { en: "Detailed Analysis", ta: "விரிவான பகுப்பாய்வு" },
  "Correct Answers": { en: "Correct Answers", ta: "சரியான பதில்கள்" },
  "Concept": { en: "Concept", ta: "கருத்து" },
  "Chapter": { en: "Chapter", ta: "அத்தியாயம்" },
  "Below Average": { en: "Below Average", ta: "சராசரிக்கும் கீழே" },
  "Average": { en: "Average", ta: "சராசரி" },
  "Attempt": { en: "Attempt", ta: "முயற்சி" },
  "All Systems Nominal": { en: "All Systems Nominal", ta: "அனைத்தும் சீராக உள்ளன" },
  "Advanced Diagnostics": { en: "Advanced Diagnostics", ta: "மேம்பட்ட கண்டறிதல்" },
  "Actionable Plan": { en: "Actionable Plan", ta: "செயல்படக்கூடிய திட்டம்" },
  "Target b > 2.5 items:": { en: "Target b > 2.5 items:", ta: "இலக்கு b > 2.5 கேள்விகள்:" },
  "Stop reviewing easy items:": { en: "Stop reviewing easy items:", ta: "எளிதான கேள்விகளை மதிப்பாய்வு செய்வதை நிறுத்துங்கள்:" },
  "Pseudo-Guessing (c)": { en: "Pseudo-Guessing (c)", ta: "ஊகிக்கும் திறன் (c)" },
  "Probability of correct response vs. Latent Ability (θ)": { en: "Probability of correct response vs. Latent Ability (θ)", ta: "சரியான பதிலின் சாத்தியக்கூறு vs திறன் (θ)" },
  "Optimal": { en: "Optimal", ta: "உகந்தது" },
  "Latent Trait (θ) Score": { en: "Latent Trait (θ) Score", ta: "மறைந்திருக்கும் திறன் (θ) மதிப்பெண்" },
  "Item Difficulty (b)": { en: "Item Difficulty (b)", ta: "கேள்வியின் கடினத்தன்மை (b)" },
  "Item Discrimination (a)": { en: "Item Discrimination (a)", ta: "கேள்வி வேறுபாடு (a)" },
  "IRT Parameters": { en: "IRT Parameters", ta: "IRT அளவீடுகள்" },
  "Excellent (0.89)": { en: "Excellent (0.89)", ta: "மிக நன்று (0.89)" },
  "Diagnostic Confidence": { en: "Diagnostic Confidence", ta: "கண்டறியும் நம்பிக்கை" },
  "Concept Gaps Identified": { en: "Concept Gaps Identified", ta: "கருத்துப் பிழைகள் கண்டறியப்பட்டன" },
  "Build endurance for difficult questions": { en: "Build endurance for difficult questions", ta: "கடினமான கேள்விகளுக்கான சகிப்புத்தன்மையை வளர்த்துக் கொள்ளுங்கள்" },
  "Above Average": { en: "Above Average", ta: "சராசரிக்கு மேல்" },

  "LATEST SCORECARD": { en: "LATEST SCORECARD", ta: "சமீபத்திய மதிப்பெண் அட்டை" },
  "ACCURACY": { en: "ACCURACY", ta: "துல்லியம்" },
  "PERCENTILE": { en: "PERCENTILE", ta: "சதவீதம்" },
  "VIEW DETAILED REPORT": { en: "VIEW DETAILED REPORT", ta: "விரிவான அறிக்கையை காண்" },
  "CORRECT ANSWERS": { en: "CORRECT ANSWERS", ta: "சரியான பதில்கள்" },
  "INCORRECT ANSWERS": { en: "INCORRECT ANSWERS", ta: "தவறான பதில்கள்" },
  "SKIPPED QUESTIONS": { en: "SKIPPED QUESTIONS", ta: "தவிர்க்கப்பட்ட கேள்விகள்" },
  "Great work": { en: "Great work", ta: "சிறப்பான செயல்பாடு" },
  "You've outperformed": { en: "You've outperformed", ta: "நீங்கள்" },
  "of participants in the": { en: "of participants in the", ta: "% பங்கேற்பாளர்களை விட" },
  "Your consistency in": { en: "Your consistency in", ta: "சிறப்பாக செயல்பட்டுள்ளீர்கள். உங்களின்" },
  "is showing significant growth.": { en: "is showing significant growth.", ta: "நிலைத்தன்மை குறிப்பிடத்தக்க வளர்ச்சியைக் காட்டுகிறது." },
  "th": { en: "th", ta: "வது" },

  "Register": { en: "Register", ta: "பதிவு செய்" },
  "Full-Syllabus Diagnostic Mode included": { en: "Full-Syllabus Diagnostic Mode included", ta: "முழு-பாடத்திட்ட கண்டறிதல் முறை சேர்க்கப்பட்டுள்ளது" },
  "Features": { en: "Features", ta: "அம்சங்கள்" },
  "Courses": { en: "Courses", ta: "படிப்புகள்" },
  "Zero cost access to study material & mini mocks": { en: "Zero cost access to study material & mini mocks", ta: "படிப்பு பொருட்கள் மற்றும் மாதிரி தேர்வுகளுக்கு இலவச அணுகல்" },
  "Verified by Senior Faculty": { en: "Verified by Senior Faculty", ta: "மூத்த ஆசிரியர்களால் சரிபார்க்கப்பட்டது" },
  "Unlimited custom tests & weakness remediation": { en: "Unlimited custom tests & weakness remediation", ta: "வரம்பற்ற விருப்ப தேர்வுகள் மற்றும் பலவீன நிவர்த்தி" },
  "Time Remaining": { en: "Time Remaining", ta: "மீதமுள்ள நேரம்" },
  "Timer": { en: "Timer", ta: "நேர அளவி" },
  "Test Packages": { en: "Test Packages", ta: "தேர்வு தொகுப்புகள்" },
  "Target Stream": { en: "Target Stream", ta: "இலக்கு துறை" },
  "System Reliability Rate": { en: "System Reliability Rate", ta: "கணினி நம்பகத்தன்மை விகிதம்" },
  "System OK": { en: "System OK", ta: "கணினி சரி" },
  "Student Sign In": { en: "Student Sign In", ta: "மாணவர் உள்நுழைவு" },
  "Strict Syllabus Match": { en: "Strict Syllabus Match", ta: "சரியான பாடத்திட்ட பொருத்தம்" },
  "Sign In": { en: "Sign In", ta: "உள்நுழைக" },
  "Select Test Program": { en: "Select Test Program", ta: "தேர்வு திட்டத்தை தேர்வு செய்யவும்" },
  "Registered Email or Mobile": { en: "Registered Email or Mobile", ta: "பதிவு செய்யப்பட்ட மின்னஞ்சல் அல்லது மொபைல்" },
  "Register Aspirant": { en: "Register Aspirant", ta: "பதிவு மாணவர்" },
  "Password": { en: "Password", ta: "கடவுச்சொல்" },
  "Lumen Academy Portal": { en: "Lumen Academy Portal", ta: "லூமென் அகாடமி போர்டல்" },
  "Master NEET with AI-Driven Precision": { en: "Master NEET with AI-Driven Precision", ta: "AI-உந்துதல் துல்லியத்துடன் NEET-ஐ வெல்லுங்கள்" },

  "Your Study Plan for 720 Marks has been activated and saved to your profile!": { en: "Your Study Plan for 720 Marks has been activated and saved to your profile!", ta: "உங்கள் 720 மதிப்பெண்களுக்கான படிப்பு திட்டம் சேமிக்கப்பட்டது!" },
  "Time-blocked routine designed for peak cognitive absorption and zero burn-out.": { en: "Time-blocked routine designed for peak cognitive absorption and zero burn-out.", ta: "அதிக அறிவாற்றல் மற்றும் சோர்வு இல்லாமல் இருப்பதற்காக வடிவமைக்கப்பட்ட நேர அட்டவணை." },
  "Target Exam Year": { en: "Target Exam Year", ta: "இலக்கு தேர்வு ஆண்டு" },
  "Primary Priority Focus": { en: "Primary Priority Focus", ta: "முதன்மையான முன்னுரிமை" },
  "Physics 180 Formula & Numerical Boost": { en: "Physics 180 Formula & Numerical Boost", ta: "இயற்பியல் 180 சூத்திரங்கள் & எண்கள் ஊக்கம்" },
  "Overall 720 Syllabus Milestones": { en: "Overall 720 Syllabus Milestones", ta: "ஒட்டுமொத்த 720 பாடத்திட்ட மைல்கற்கள்" },
  "Organic & Inorganic Chem Mastery": { en: "Organic & Inorganic Chem Mastery", ta: "கரிம & கனிம வேதியியல் தேர்ச்சி" },
  "NEET 2027 (2-Year Roadmap)": { en: "NEET 2027 (2-Year Roadmap)", ta: "NEET 2027 (2-ஆண்டு வரைபடம்)" },
  "NEET 2026 (Target May 2026)": { en: "NEET 2026 (Target May 2026)", ta: "NEET 2026 (இலக்கு மே 2026)" },
  "Mark off chapters as you complete revision & mock questions.": { en: "Mark off chapters as you complete revision & mock questions.", ta: "திருப்புதல் மற்றும் மாதிரி கேள்விகளை முடித்தவுடன் அத்தியாயங்களை குறிக்கவும்." },
  "Journey to 720 starts here": { en: "Journey to 720 starts here", ta: "720 நோக்கிய பயணம் இங்கே தொடங்குகிறது" },
  "Daily Study Target": { en: "Daily Study Target", ta: "தினசரி படிப்பு இலக்கு" },
  "Current Score Level": { en: "Current Score Level", ta: "தற்போதைய மதிப்பெண் நிலை" },
  "Biology 360/360 NCERT Lock": { en: "Biology 360/360 NCERT Lock", ta: "உயிரியல் 360/360 NCERT உறுதி" },
  "Below 450 Marks (Foundation Push)": { en: "Below 450 Marks (Foundation Push)", ta: "450 மதிப்பெண்களுக்குக் கீழே (அடிப்படை ஊக்கம்)" },
  "Balanced All-Subject 720 Sprint": { en: "Balanced All-Subject 720 Sprint", ta: "சமநிலையான அனைத்து பாட 720 ஓட்டம்" },
  "Adjust your prep profile to update your daily hourly routine and milestone map in real-time.": { en: "Adjust your prep profile to update your daily hourly routine and milestone map in real-time.", ta: "உங்கள் தினசரி அட்டவணையை புதுப்பிக்க உங்கள் படிப்பு சுயவிவரத்தை சரிசெய்யவும்." },
  "90 Questions • 100% NCERT Line-by-Line Mastery. Biology is your rank foundation anchor.": { en: "90 Questions • 100% NCERT Line-by-Line Mastery. Biology is your rank foundation anchor.", ta: "90 கேள்விகள் • 100% NCERT தேர்ச்சி. உயிரியல் உங்கள் தரவரிசை அடிப்படை." },
  "8 Hours / Day (Balanced Standard)": { en: "8 Hours / Day (Balanced Standard)", ta: "8 மணிநேரம் / நாள் (சமநிலையானது)" },
  "600+ Marks (Rank Booster)": { en: "600+ Marks (Rank Booster)", ta: "600+ மதிப்பெண்கள் (தரவரிசை உயர்த்துபவர்)" },
  "45 Hours Required": { en: "45 Hours Required", ta: "45 மணிநேரம் தேவை" },
  "450 - 600 Marks (Consolidation)": { en: "450 - 600 Marks (Consolidation)", ta: "450 - 600 மதிப்பெண்கள் (ஒருங்கிணைப்பு)" },
  "180 / 180 Marks": { en: "180 / 180 Marks", ta: "180 / 180 மதிப்பெண்கள்" },
  "12 Hours / Day (Aggressive Revision)": { en: "12 Hours / Day (Aggressive Revision)", ta: "12 மணிநேரம் / நாள் (தீவிர திருப்புதல்)" },
  "10 Hours / Day (Intensive Push)": { en: "10 Hours / Day (Intensive Push)", ta: "10 மணிநேரம் / நாள் (தீவிர ஊக்கம்)" },

  "Your Score": { en: "Your Score", ta: "உங்கள் மதிப்பெண்" },
  "Topics:": { en: "Topics:", ta: "தலைப்புகள்:" },
  "Accuracy": { en: "Accuracy", ta: "துல்லியம்" },
  "Focus Subject": { en: "Focus Subject", ta: "கவனிக்க வேண்டிய பாடம்" },
  "Where You Lagged:": { en: "Where You Lagged:", ta: "நீங்கள் பின்தங்கிய இடங்கள்:" },
  "Top 5%": { en: "Top 5%", ta: "சிறந்த 5%" },
  "Your cognitive trait level is well above the average participant pool.": { en: "Your cognitive trait level is well above the average participant pool.", ta: "உங்கள் அறிவாற்றல் திறன் சராசரி பங்கேற்பாளர்களை விட மிக அதிகம்." },
  "You consistently correctly answer items with a difficulty parameter (b) > 2.0.": { en: "You consistently correctly answer items with a difficulty parameter (b) > 2.0.", ta: "கடினமான கேள்விகளுக்கு நீங்கள் தொடர்ந்து சரியாக பதிலளிக்கிறீர்கள்." },
  "You answered all tested NCERT syllabus units with high precision. Keep maintaining this streak.": { en: "You answered all tested NCERT syllabus units with high precision. Keep maintaining this streak.", ta: "சோதிக்கப்பட்ட அனைத்து NCERT பாடத்திட்டங்களுக்கும் நீங்கள் துல்லியமாக பதிலளித்துள்ளீர்கள்." },
  "Item Response Theory (IRT) Analysis": { en: "Item Response Theory (IRT) Analysis", ta: "கேள்வி பதில் கோட்பாடு (IRT) பகுப்பாய்வு" },
  "Based on 2-Parameter Logistic Model (2PL)": { en: "Based on 2-Parameter Logistic Model (2PL)", ta: "2-Parameter Logistic Model (2PL) அடிப்படையில்" },
  "Theta (θ) - Ability Level": { en: "Theta (θ) - Ability Level", ta: "Theta (θ) - திறன் நிலை" },
  "You (+1.84)": { en: "You (+1.84)", ta: "நீங்கள் (+1.84)" },
  "Population Avg (0.0)": { en: "Population Avg (0.0)", ta: "சராசரி (0.0)" },
  "Item Difficulty (b) vs. Probability": { en: "Item Difficulty (b) vs. Probability", ta: "கேள்வி கடினம் (b) vs. சாத்தியக்கூறு" },
  "High Discrimination Items": { en: "High Discrimination Items", ta: "அதிக வேறுபாட்டு கேள்விகள்" },
  "You correctly answered 8 out of 10 items that highly discriminate between top and bottom performers (a > 1.5).": { en: "You correctly answered 8 out of 10 items that highly discriminate between top and bottom performers (a > 1.5).", ta: "சிறந்த மற்றும் குறைந்த செயல்திறன் கொண்டவர்களை வேறுபடுத்தும் 10 இல் 8 கேள்விகளுக்கு சரியாக பதிலளித்துள்ளீர்கள்." },
  "Guessing Parameter (c)": { en: "Guessing Parameter (c)", ta: "ஊகிக்கும் திறன் (c)" },
  "With a pseudo-guessing parameter (c) of just 12%, your score is robust and not inflated by chance.": { en: "With a pseudo-guessing parameter (c) of just 12%, your score is robust and not inflated by chance.", ta: "12% ஊகிக்கும் திறனுடன், உங்கள் மதிப்பெண் வலுவானது, வாய்ப்பால் உயர்ந்ததல்ல." },
  "Close IRT Report": { en: "Close IRT Report", ta: "IRT அறிக்கையை மூடு" },
  "Test Mode": { en: "Test Mode", ta: "தேர்வு முறை" },
  "Standard Mode": { en: "Standard Mode", ta: "நிலையான முறை" },
  "Exam Environment": { en: "Exam Environment", ta: "தேர்வு சூழல்" },
  "Exam Engine Diagnostics": { en: "Exam Engine Diagnostics", ta: "தேர்வு இயந்திர கண்டறிதல்" },
  "System Status": { en: "System Status", ta: "கணினி நிலை" },
  "Network Latency": { en: "Network Latency", ta: "நெட்வொர்க் தாமதம்" },
  "Good (24ms)": { en: "Good (24ms)", ta: "நன்று (24ms)" },
  "Questions Available": { en: "Questions Available", ta: "கிடைக்கும் கேள்விகள்" },
  "Question Selection": { en: "Question Selection", ta: "கேள்வி தேர்வு" },
  "Generate Custom Test": { en: "Generate Custom Test", ta: "விருப்ப தேர்வை உருவாக்கு" },
  "Current Focus Areas": { en: "Current Focus Areas", ta: "தற்போதைய கவனம் செலுத்தும் பகுதிகள்" },
  "Critical Weakness": { en: "Critical Weakness", ta: "மிகவும் பலவீனமானவை" },
  "Improvement Area": { en: "Improvement Area", ta: "மேம்படுத்த வேண்டியவை" },
  "Mastered": { en: "Mastered", ta: "நன்கு கற்றவை" },
  "Recent Activity": { en: "Recent Activity", ta: "சமீபத்திய செயல்பாடு" },
  "Completed Biology Chapter 4": { en: "Completed Biology Chapter 4", ta: "உயிரியல் அத்தியாயம் 4 முடிந்தது" },
  "Yesterday": { en: "Yesterday", ta: "நேற்று" },
  "Scored 92% in Full Mock Test": { en: "Scored 92% in Full Mock Test", ta: "முழு மாதிரி தேர்வில் 92% மதிப்பெண்" },
  "2 days ago": { en: "2 days ago", ta: "2 நாட்களுக்கு முன்" },
  "Studied Physics for 3 hours": { en: "Studied Physics for 3 hours", ta: "இயற்பியல் 3 மணி நேரம் படிக்கப்பட்டது" },
  "3 days ago": { en: "3 days ago", ta: "3 நாட்களுக்கு முன்" },
  "Overall Readiness": { en: "Overall Readiness", ta: "ஒட்டுமொத்த தயார்நிலை" },
  "Projected Rank": { en: "Projected Rank", ta: "கணிக்கப்பட்ட தரவரிசை" },
  "Target: < 5000": { en: "Target: < 5000", ta: "இலக்கு: < 5000" },
  "Estimated AIR": { en: "Estimated AIR", ta: "கணிக்கப்பட்ட AIR" },
  "Start Diagnostics": { en: "Start Diagnostics", ta: "பகுப்பாய்வை தொடங்கு" },
  "AI generating report...": { en: "AI generating report...", ta: "AI அறிக்கை தயாரிக்கிறது..." },
  "Close Report": { en: "Close Report", ta: "அறிக்கையை மூடு" },
  "Save Preferences": { en: "Save Preferences", ta: "விருப்பங்களை சேமி" },
  "Cancel": { en: "Cancel", ta: "ரத்துசெய்" },
  "Current Password": { en: "Current Password", ta: "தற்போதைய கடவுச்சொல்" },
  "New Password": { en: "New Password", ta: "புதிய கடவுச்சொல்" },

  "Welcome back": { en: "Welcome back", ta: "மீண்டும் வருக" },
  "TOTAL SCORE": { en: "TOTAL SCORE", ta: "மொத்த மதிப்பெண்" },
  "Total Score": { en: "Total Score", ta: "மொத்த மதிப்பெண்" },
  "Correct": { en: "Correct", ta: "சரியானவை" },
  "Incorrect": { en: "Incorrect", ta: "தவறானவை" },
  "Skipped": { en: "Skipped", ta: "தவிர்க்கப்பட்டவை" },
  "Average Time/Question": { en: "Average Time/Question", ta: "சராசரி நேரம்/கேள்வி" },
  "Percentile": { en: "Percentile", ta: "சதவீதம்" },
  "View Detailed Analytics": { en: "View Detailed Analytics", ta: "விரிவான பகுப்பாய்வை காண்" },
  "Recent Test Performance": { en: "Recent Test Performance", ta: "சமீபத்திய தேர்வு செயல்பாடு" },
  "Subject-Wise Accuracy": { en: "Subject-Wise Accuracy", ta: "பாடம் சார்ந்த துல்லியம்" },
  "Biology": { en: "Biology", ta: "உயிரியல்" },
  "Physics": { en: "Physics", ta: "இயற்பியல்" },
  "Chemistry": { en: "Chemistry", ta: "வேதியியல்" },
  "Botany": { en: "Botany", ta: "தாவரவியல்" },
  "Zoology": { en: "Zoology", ta: "விலங்கியல்" },
  "Weak Topics (AI Identified)": { en: "Weak Topics (AI Identified)", ta: "பலவீனமான தலைப்புகள் (AI கண்டறிந்தது)" },
  "Strong Topics": { en: "Strong Topics", ta: "வலுவான தலைப்புகள்" },
  "Start Next Test": { en: "Start Next Test", ta: "அடுத்த தேர்வை தொடங்கு" },
  "Available Tests": { en: "Available Tests", ta: "கிடைக்கும் தேர்வுகள்" },
  "Start Test": { en: "Start Test", ta: "தேர்வை தொடங்கு" },
  "Resume Test": { en: "Resume Test", ta: "தேர்வை தொடரவும்" },
  "Completed": { en: "Completed", ta: "முடிந்தது" },
  "Practice": { en: "Practice", ta: "பயிற்சி" },
  "Custom Test": { en: "Custom Test", ta: "விருப்ப தேர்வு" },
  "Duration": { en: "Duration", ta: "கால அளவு" },
  "Questions": { en: "Questions", ta: "கேள்விகள்" },
  "Submit Test?": { en: "Submit Test?", ta: "தேர்வை சமர்ப்பிக்கவா?" },
  "Submit Anyway": { en: "Submit Anyway", ta: "அப்படியே சமர்ப்பி" },
  "Submit Test": { en: "Submit Test", ta: "தேர்வை சமர்ப்பி" },
  "Go Back & Review": { en: "Go Back & Review", ta: "திரும்பிச் சென்று சரிபார்க்கவும்" },
  "TIME REMAINING": { en: "TIME REMAINING", ta: "மீதமுள்ள நேரம்" },
  "Mark for Review": { en: "Mark for Review", ta: "மதிப்பாய்வுக்கு குறிக்க" },
  "Clear Response": { en: "Clear Response", ta: "பதிலை அழி" },
  "Next Question": { en: "Next Question", ta: "அடுத்த கேள்வி" },
  "Previous Question": { en: "Previous Question", ta: "முந்தைய கேள்வி" },
  "Question Panel": { en: "Question Panel", ta: "கேள்வி பலகை" },
  "Not Visited": { en: "Not Visited", ta: "பார்க்காதவை" },
  "Not Answered": { en: "Not Answered", ta: "பதிலளிக்காதவை" },
  "Answered": { en: "Answered", ta: "பதிலளித்தவை" },
  "Marked for Review": { en: "Marked for Review", ta: "மதிப்பாய்வுக்கு குறிக்கப்பட்டவை" },
  "Answered & Marked for Review": { en: "Answered & Marked for Review", ta: "பதிலளித்து மதிப்பாய்வுக்கு குறிக்கப்பட்டவை" },
  "Study Plan": { en: "Study Plan", ta: "படிப்பத்திட்டம்" },
  "Syllabus Completion": { en: "Syllabus Completion", ta: "பாடத்திட்ட நிறைவு" },
  "Chapters Completed": { en: "Chapters Completed", ta: "முடிக்கப்பட்ட அத்தியாயங்கள்" },
  "High Yield Topics": { en: "High Yield Topics", ta: "அதிக மதிப்பெண் தலைப்புகள்" },
  "Continue Learning": { en: "Continue Learning", ta: "படிப்பை தொடரவும்" },
  "Video Lectures": { en: "Video Lectures", ta: "காணொளி விரிவுரைகள்" },
  "Study Materials": { en: "Study Materials", ta: "படிப்பு பொருட்கள்" },
  "Growth Trend": { en: "Growth Trend", ta: "வளர்ச்சி போக்கு" },
  "Accuracy Rate": { en: "Accuracy Rate", ta: "துல்லிய விகிதம்" },
  "Time Taken": { en: "Time Taken", ta: "எடுத்துக்கொண்ட நேரம்" },
  "Time Speed": { en: "Time Speed", ta: "நேர வேகம்" },
  "Back to Scorecard": { en: "Back to Scorecard", ta: "மதிப்பெண் அட்டைக்கு திரும்புக" },
  "Where You Lagged": { en: "Where You Lagged", ta: "நீங்கள் பின்தங்கிய இடங்கள்" },
  "Performance Graph": { en: "Performance Graph", ta: "செயல்திறன் வரைபடம்" },
  "DASHBOARD": { en: "DASHBOARD", ta: "டாஷ்போர்டு" },
  "COURSE": { en: "COURSE", ta: "படிப்புகள்" },
  "TESTS": { en: "TESTS", ta: "தேர்வுகள்" },
  "ANALYTICS": { en: "ANALYTICS", ta: "பகுப்பாய்வு" },
  "Sign Out": { en: "Sign Out", ta: "வெளியேறு" },
  "View Syllabus": { en: "View Syllabus", ta: "பாடத்திட்டத்தை பார்க்கவும்" },
  "Filter by Subject": { en: "Filter by Subject", ta: "பாடவாரியாக வடிகட்டவும்" },
  "Start Full Mock Test": { en: "Start Full Mock Test", ta: "முழு மாதிரி தேர்வை தொடங்கு" },
  "Create Custom Test": { en: "Create Custom Test", ta: "விருப்ப தேர்வை உருவாக்கு" },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ta' : 'en');
  };

  const t = (key: string): string => {
    return translations[key]?.[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
